list: $/gemfourmedia/gfaqs/models/category/columns.yaml
modelClass: GemFourMedia\GFAQs\Models\Category
title: Category
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gemfourmedia/gfaqs/category/update/:id'