list: $/gemfourmedia/gfaqs/models/question/columns.yaml
modelClass: GemFourMedia\GFAQs\Models\Question
title: Question
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gemfourmedia/gfaqs/question/update/:id'
filter: config_filter.yaml